[build]
  command = "ESLINT_NO_DEV_ERRORS=true npm run build --legacy-peer-deps"
  publish = "dist"

[build.environment]
  NETLIFY_SKIP_INSTALL = "true"
  NODE_VERSION = "20"

[redirects]
  from = "/*"
  to = "/index.html"
  status = 200
